name: church_app
description: "Connect with the Church"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^8.0.5
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  iconly: ^1.0.1
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  lottie: ^3.1.2
  open_file: ^3.3.2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.6
  url_launcher: ^6.3.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  flutter_switch: ^0.3.2
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  firebase_ui_auth: ^1.15.0
  change_app_package_name: ^1.2.0
  form_builder_extra_fields: ^10.2.0
  form_builder_image_picker: ^4.0.0
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  get: ^4.6.6
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  flutter_phone_direct_caller: ^2.1.0
  mailer: ^6.1.2


dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

